# Generated by Django 5.2.14 on 2026-05-26 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='example',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='translation',
            options={'ordering': ['order']},
        ),
    ]
